### ISSUE TITLE
Print current working directory for "Command failed"

### ISSUE THREAD

**Issue by vorburger** [JoseVSeb/google-java-format-for-vs-code#21]
In an ideal world, it would be slightly more user friendly if when it fails and logs `Command failed`, it would include the current working directory.

This would have made debugging #20 a tiny bit more convenient. (Because it took me an instant to figure out that `./google-java-format_linux-x86-64` is in ~/.vscode/extensions/josevseb.google-java-format-for-vs-code-1.1.0/cache/b2...dc/`.)

**Comment by JoseVSeb** [comment]
i have added debug log when cwd is set.
