### ISSUE TITLE
Error "command googleJavaFormatForVSCode.reloadExectuable not found" after changing the version

### ISSUE THREAD

**Issue by NathanielRN** [JoseVSeb/google-java-format-for-vs-code#52]
## Problem

This extension was working great, but now I cannot get it to even load.

I was using the `"java.format.settings.google.version"` to switch between `latest` and `1.0`. I was clicking "OK" on the extension's prompt to reload the extension and using `Developer: Reload Window` to make sure the changes take effect.

Somewhere between testing the versions I found myself getting this VSCode error:
<img width="281" alt="Google VSCode Format Ext not found" src="https://github.com/JoseVSeb/google-java-format-for-vs-code/assets/23139455/a80c68fa-fdd1-41b4-ad01-0f7b171194ec">

All of sudden the extension's command are not there...

I tried to "uninstall" and "install" several times, install from `.VSIX`, and disable/enabled it but nothing works. I tried `npm install` on the folder directly but still the command is not registered.

Do you know if there is some caching going on here that is causing me to not get any of the extension commands installed?

**Comment by JoseVSeb** [comment]
are you still facing this issue?

if yes, please set log level to debug and provide the log of this extension from output tab

**Comment by NathanielRN** [comment]
Yes I am still facing this issue.

> if yes, please set log level to debug and provide the log of this extension from output tab

There's not much here... If I run `Format Document` I see these logs:

```
2024-05-29 16:23:44.721 [debug] Cache directory created at file:///Users/enowell/.vscode/extensions/josevseb.google-java-format-for-vs-code-1.1.2/cache
2024-05-29 16:23:44.721 [debug] Using native binary for darwin-x64 if available
2024-05-29 16:23:44.721 [debug] Calling "" with arguments: ["1.0"]
2024-05-29 16:23:44.721 [debug] Fetching: https://api.github.com/repos/google/google-java-format/releases/tags/v1.0
2024-05-29 16:23:45.224 [error] Error in "": Failed to get v1.0 of Google Java Format.
```

and this error message:

<img width="282" alt="image" src="https://github.com/JoseVSeb/google-java-format-for-vs-code/assets/23139455/18e0a615-5b25-48d4-95df-7345c94a099f">

If I run `Google Java Format for VS Code: Reload Executable`, I get the same error message from above.

This is all after uninstalling and reinstalling. I also delete the package from the VSCode `Library/` `Application Support/` folder and it still fails like this.

**Comment by JoseVSeb** [comment]
thanks for the log.
it seems like versions before `v1.10.0` are tagged differently in the GitHub releases.
for now, you can use `https://github.com/google/google-java-format/releases/download/google-java-format-1.0/google-java-format-1.0-all-deps.jar` in setting `java.format.settings.google.executable` to load `v1.0` although I'm not sure if the CLI arguments are the same.
you can raise a PR if you have a fix.

**Comment by NathanielRN** [comment]
Thank you for your response!

Adding the setting didn't work for me, but your comment helped me resolve the problem!

I uninstalled the extension and installed directly from GitHub by downloaded the latest downloaded `.vsix` file. Next, I uninstalled it form the VSCode extension page and re-installed it again after that to get `1.0` again.

Now it finally works! I guess my cache was in a weird state between versions? But just happy it works again :)

Before I close it, do you think it would worthwhile for me to add a message to the warning dialog that says "Try downloading this from GitHub directly"?
